package com.titan1um.specialswords.sword;
import com.titan1um.specialswords.SwordUtils;
import net.minecraft.enchantment.*;import net.minecraft.entity.*;import net.minecraft.item.*;import net.minecraft.network.packet.s2c.play.EntityVelocityUpdateS2CPacket;import net.minecraft.server.*;import net.minecraft.server.network.ServerPlayerEntity;import net.minecraft.server.world.ServerWorld;import net.minecraft.sound.*;import net.minecraft.util.*;import net.minecraft.util.math.*;import net.minecraft.world.WorldEvents;import java.util.*;
public final class DashSword{
 private static final long FCD=3000,UCD=10000,MCD=30000;private static final Map<UUID,Long>FC=new HashMap<>(),UC=new HashMap<>(),MC=new HashMap<>();private static final Map<UUID,State>UP=new HashMap<>();private static final Map<UUID,Vec3d>FD=new HashMap<>();
 private DashSword(){}
 public static boolean matches(ItemStack s){return SwordUtils.isSpecialSword(s,SwordUtils.DASH_SWORD);}
 public static ActionResult tryActivate(ServerPlayerEntity p,ItemStack s,Hand h){
  if(!matches(s))return ActionResult.PASS;boolean up=p.getPitch()<=-60;
  if(up){long r=rem(UC,p.getUuid());if(r>0){SwordUtils.cooldown(p,"Upward Dash",r);return ActionResult.FAIL;}UC.put(p.getUuid(),System.currentTimeMillis()+UCD);UP.put(p.getUuid(),new State());p.setVelocity(new Vec3d(p.getVelocity().x,1.75,p.getVelocity().z));p.velocityDirty=true;p.fallDistance=0;wind(p);s.damage(10,p,h);sound(p);SwordUtils.bar(p,"Upward Dash activated!",Formatting.GREEN);send(p);return ActionResult.SUCCESS;}
  long r=rem(FC,p.getUuid());if(r>0){SwordUtils.cooldown(p,"Forward Dash",r);return ActionResult.FAIL;}Vec3d d=p.getRotationVector();d=new Vec3d(d.x,0,d.z);if(d.lengthSquared()<.0001)d=new Vec3d(0,0,1);FD.put(p.getUuid(),d.normalize());FC.put(p.getUuid(),System.currentTimeMillis()+FCD);s.damage(5,p,h);sound(p);SwordUtils.bar(p,"Forward Dash activated!",Formatting.GREEN);return ActionResult.SUCCESS;
 }
 public static void tick(MinecraftServer s){for(ServerPlayerEntity p:s.getPlayerManager().getPlayerList())if(holding(p))p.fallDistance=0;tickF(s);tickU(s);}
 public static boolean shouldCancelFallDamage(ServerPlayerEntity p){return holding(p)||UP.containsKey(p.getUuid());}
 private static boolean holding(ServerPlayerEntity p){return matches(p.getMainHandStack());}
 private static void tickF(MinecraftServer s){Iterator<Map.Entry<UUID,Vec3d>>it=FD.entrySet().iterator();while(it.hasNext()){var e=it.next();ServerPlayerEntity p=s.getPlayerManager().getPlayer(e.getKey());if(p==null){it.remove();continue;}p.setVelocity(e.getValue().multiply(1.17));p.velocityDirty=true;send(p);if(p.horizontalCollision||p.isOnGround()&&p.getVelocity().horizontalLength()<.1)it.remove();}}
 private static void tickU(MinecraftServer s){Iterator<Map.Entry<UUID,State>>it=UP.entrySet().iterator();while(it.hasNext()){var e=it.next();ServerPlayerEntity p=s.getPlayerManager().getPlayer(e.getKey());if(p==null){it.remove();continue;}State st=e.getValue();p.fallDistance=0;if(p.getVelocity().y<-.05)st.falling=true;if(st.falling&&p.isOnGround()){if(holding(p)&&rem(MC,p.getUuid())==0){smash(p);MC.put(p.getUuid(),System.currentTimeMillis()+MCD);}it.remove();continue;}if(++st.ticks>600)it.remove();}}
 private static void smash(ServerPlayerEntity a){ServerWorld w=a.getEntityWorld();List<LivingEntity>ts=w.getEntitiesByClass(LivingEntity.class,a.getBoundingBox().expand(5),t->t!=a&&t.isAlive()&&t.squaredDistanceTo(a)<=25);var src=w.getDamageSources().maceSmash(a);ItemStack m=new ItemStack(Items.MACE);var reg=w.getRegistryManager().getOrThrow(net.minecraft.registry.RegistryKeys.ENCHANTMENT);m.addEnchantment(reg.getOrThrow(Enchantments.DENSITY),5);m.addEnchantment(reg.getOrThrow(Enchantments.BREACH),4);w.syncWorldEvent(a,WorldEvents.SMASH_ATTACK,a.getBlockPos(),750);w.playSound(null,a.getX(),a.getY(),a.getZ(),SoundEvents.ITEM_MACE_SMASH_GROUND_HEAVY,SoundCategory.PLAYERS,1,1);boolean hit=false;for(LivingEntity t:ts){float per=EnchantmentHelper.getSmashDamagePerFallenBlock(w,m,t,src,.5f);if(t.damage(w,src,EnchantmentHelper.getDamage(w,m,t,src,8+14*per)))hit=true;}if(hit&&matches(a.getMainHandStack()))a.getMainHandStack().damage(15,a,EquipmentSlot.MAINHAND);}
 private static void wind(ServerPlayerEntity p){ServerWorld w=p.getEntityWorld();for(LivingEntity t:w.getEntitiesByClass(LivingEntity.class,p.getBoundingBox().expand(8),x->x!=p&&x.isAlive()&&x.squaredDistanceTo(p)<=64)){Vec3d d=t.getEntityPos().subtract(p.getEntityPos());double h=Math.sqrt(d.x*d.x+d.z*d.z);if(h<.001)continue;double k=1.5*(1-Math.min(8,h)/8);t.addVelocity(d.x/h*k,.55,d.z/h*k);t.velocityDirty=true;}w.playSound(null,p.getX(),p.getY(),p.getZ(),SoundEvents.ENTITY_BREEZE_WIND_BURST,SoundCategory.PLAYERS,1,1);}
 private static void sound(ServerPlayerEntity p){p.getEntityWorld().playSound(null,p.getX(),p.getY(),p.getZ(),SoundEvents.ITEM_SPEAR_LUNGE_1,SoundCategory.PLAYERS,1,1);}
 private static void send(ServerPlayerEntity p){p.networkHandler.sendPacket(new EntityVelocityUpdateS2CPacket(p));}
 private static long rem(Map<UUID,Long>m,UUID u){Long x=m.get(u);if(x==null)return 0;long r=x-System.currentTimeMillis();if(r<=0){m.remove(u);return 0;}return r;}
 private static final class State{int ticks;boolean falling;}
}